server:
  port: 9005
  servlet:
    contextPath: /location

spring:
  data:
    mongodb:
      uri: mongodb://poppin:rkcjseo123!@175.197.99.131:30017/location

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org.springframework.data.mongodb: DEBUG

